name: Update blog resume data

on:
  push:
    branches:
      - brunopc
    paths:
      - public/resume.json
    
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout brunopc branch
      uses: actions/checkout@v3
      with:
        ref: brunopc

    - name: Set up Git user
      run: |
        git config --global user.name 'Bruno PC'
        git config --global user.email 'brunopc-net@users.noreply.github.com'

    - name: Clone Docusaurus-Blog repository
      uses: actions/checkout@v3
      with:
        repository: brunopc-net/Docusaurus-Blog
        ref: gh-pages
        path: Docusaurus-Blog

    - name: Update resume.json file
      run: |
        cp public/resume.json Docusaurus-Blog/data/

    - name: Commit changes
      run: |
        cd Docusaurus-Blog
        git add data/resume.json
        git commit -m "Reactsume updates resume.json"

    - name: Set SSH deploy key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}

    - name: Push changes
      run: |
        git push